# Generated by Django 4.1 on 2023-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacao',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
