# Generated by Django 4.1 on 2023-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_alter_informacao_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacao',
            name='image',
        ),
        migrations.AddField(
            model_name='informacao',
            name='titulo',
            field=models.CharField(default='Quem somos', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacao',
            name='texto',
            field=models.CharField(max_length=700),
        ),
    ]
