# Generated by Django 4.1 on 2023-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_remove_informacao_image_informacao_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='image',
            field=models.CharField(default='ic.png', max_length=100),
            preserve_default=False,
        ),
    ]
